### ISSUE TITLE
Jersey dependency for docker-client

### ISSUE THREAD

**Issue by JWGmeligMeyling** [spotify/docker-client#107]
This is not really an issue but more of a question. I wanted to integrate the `docker-client` into a project that uses another `HttpClient`, in this case the `Resteasy` client. I ran into some problems because the `DefaultDockerClient` was dependent on the Jersey Client. I was wondering if it maybe was possible to write this more generic against the `HttpClient` interfaces or if it would be an idea to move the `HttpClient` providing  logic out of the `DefaultDockerClient`, so that the remaining parts can be reused for implementations with other clients. I'd like to hear you thoughts on this. :smile: 

**Edit:**
A small update on this thread: I've managed to get the tests to pass on a Resteasy client, but it involved quite a lot of work, mostly due to Resteasy only working with an older HTTP client. For the ones interested in the changes, [this](https://github.com/JWGmeligMeyling/docker-client/commit/a7f15377238fd255b31db73247e1a6c7e42eb8f8#commitcomment-9093093) is the commit, which also has some comments attached.

**Comment by rohansingh** [comment]
We've actually run into a number of issues due to the vagaries of behavior of different HTTP clients. For example, we had a whole slew of bugs that came out of switching from `HttpUrlConnection` to the Apache client (both being used under the covers by Jersey).

I get the desire to use different clients, but due to the support effort involved, we're unlikely to ever include official support for more than one client.

In terms of having this be pluggable so users can provide their own implementations —again, I see the use case, but I don't see us supporting this since it introduces an additional layer of abstraction in service of an objective that doesn't really align with what we're trying to do (i.e., provide a straightforward Docker client that just works). If this is really something that you need, it might be a good case for a fork.

Disclaimer: these are all just my thoughts, the other Spotify maintainers may think differently.

**Comment by davidxia** [comment]
I'm leaning towards @rohansingh's suggestion. Should we close this issue?

**Comment by JWGmeligMeyling** [comment]
It can be closed.
