### ISSUE TITLE
Could you explain for List Images using filters?

### ISSUE THREAD

**Issue by bwahn** [spotify/docker-client#180]
I wrote as referenced "public List<Image> listImages(ListImagesParam... params)" functions of DefaultDockerClient.java, I show the code as below :
Could you explain what kind of filter is it?

        final Map<String, String> filters =  newHashMap();
        filters.put("RepoTags", "nginx");

        final StringWriter writer = new StringWriter();

        try {
            final JsonGenerator generator = ObjectMapperProvider.objectMapper().getFactory().createGenerator(writer);
            generator.writeStartObject();
            for (Map.Entry<String, String> entry : filters.entrySet()) {
                generator.writeArrayFieldStart(entry.getKey());
                generator.writeString(entry.getValue());
                generator.writeEndArray();
            }
            generator.writeEndObject();
            generator.close();

            final String encoded = URLEncoder.encode(writer.toString(), UTF_8.name());

            ResponseResult result = WS2.get(dockerHost + "/images/json?filters=" + encoded);

==> It has error messages from Docker host.
statusCode":500,"statusText":"Internal Server Error"}
[debug] application - get:http://172.17.8.101:2375/images/json?filters=%7B%22repo%22%3A%5B%22nginx%3Alatest%22%5D%7D
[debug] application - 500:Internal Server Error
[debug] application - Invalid filter 'repo'

**Comment by davidxia** [comment]
@bwahn According to the [Docker API docs](https://docs.docker.com/reference/api/docker_remote_api_v1.18/#list-images):

> * filters – a json encoded value of the filters (a map[string][]string) to process on the images list. Available filters:
>   * dangling=true

**Comment by bwahn** [comment]
@davidxia , 
How can I handle the filters? 
Can you review it?
```
final Map<String, String> filters =  newHashMap();
filters.put("RepoTags", "nginx");
```

**Comment by davidxia** [comment]
I haven't tried this before, but it looks like the tag isn't valid.

**Comment by bwahn** [comment]
It's not valid.
I got error message "[debug] application - Invalid filter 'repo'" from Docker Host installed coreos.

**Comment by davidxia** [comment]
Yea that makes sense because that tag isn't listed in the docs as a valid tag. I'm not sure I understand your question.

**Comment by davidxia** [comment]
@bwahn Let me know if still have this question or if I can close this issue.

**Comment by bwahn** [comment]
@davidxia Sure, Please close this issue. I will ask later.

**Comment by johnflavin** [comment]
Vote to reopen.

I think the issue here is the difference between the query params "filter" and "filter*s*". From the [Remote API docs](https://docs.docker.com/reference/api/docker_remote_api_v1.22/#list-images):

> * filters – a JSON encoded value of the filters (a map[string][]string) to process on the images list. Available filters:
 `dangling=true`
 `label=key` or `label="key=value"` of an image label

> * filter - only return images with the specified name

It looks like @bwahn is trying to use the latter, but the `listImages` method only supports the former. 

I think this would be a useful feature. On its face it seems to duplicate functionality; one can already use `inspectImage(name)` to query about a particular tagged image, so why support `listImages` with `filter=name`? The reason is that they return different information. The former returns an `ImageInfo` and the latter a `List` of `Image`s. Both are useful, and the information in either object doesn't completely overlap the other. (Specifically, `ImageInfo` does not contain the image's `Labels`. For some reason Docker doesn't report those on `GET /images/(name)/json`.)
