### ISSUE TITLE
Client not compatible with Docker 1.7.0 / API version 1.19

### ISSUE THREAD

**Issue by paulrutter** [spotify/docker-client#229]
The readme.txt states that the client is only tested up until API version 1.18.
When using the new Docker (1.7.0, although 1.8.0 is out), which ships with API version 1.19, starting a container no longer works.

The following error occurs:

`com.spotify.docker.client.DockerRequestException: Request error: POST `unix://localhost:80/v1.12/containers/7092895be5f0c394869020a99f6565c180905d56f374a28dd66190`b4c9681ac7/start: 500

Are you planning to support the newer API versions?
That would be great :+1:

**Comment by rgrunber** [comment]
The README probably need to be updated. I have been testing the client against the 1.19 API and the only place I found additional changes necessary were spotify/docker-client@a3070c7a9b03be33be1c90f4beca43cb387a74c4  since the only breaking changes I see from 1.18 -> 1.19 were in the boolean fields. Is that backquote (`) in the container id actually printed ? Maybe a snippet of how you're using the client might help.

Just a few questions that might help narrow this down :

* What happens when you start the same container using the normal docker command line client ? (docker start CONTAINER_ID)
* What happens if you attempt to start the same container when using the docker-client library with a docker daemon configured for the 1.18 API ?

**Comment by paulrutter** [comment]
Thanks for your response. I will answer your questions tomorrow, when i have access to my test environment again.
When running Docker 1.6.1 (API 1.18), starting a container doesn't give an error.

**Comment by paulrutter** [comment]
Thanks for thinking along @rgrunber.
I tested it today after some cleanup of old images, containers and dead processes; and magically, it works without any errors. 
I'll close this issue as it our own server seems to have caused the issue.
