### ISSUE TITLE
Is there simple way to get json format?

### ISSUE THREAD

**Issue by stream1984** [spotify/docker-client#299]
Hi, i wanna convert object of ContainerInfo to json format, i think that must have a simple way since docker-client dependency jackson, but i don't know how to convert it to raw json format.
Thanks.

**Comment by mattnworb** [comment]
You can pass a ContainerInfo instance to ObjectMapper methods that convert the POJO to a String, you would just need to [register the same modules that docker-client does](https://github.com/spotify/docker-client/blob/5eca49a52e70581e50392f396bf3cbca874dc1ef/src/main/java/com/spotify/docker/client/ObjectMapperProvider.java#L66) so that ImmutableLists and ImmutableSets can be serialized properly.

```java
public class ContainerInfoTest {

  public static void main(String[] args) throws Exception {
    final ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new GuavaModule());

    // map from JSON -> ContainerInfo since the class has no mutators
    final ObjectNode objectNode = mapper.createObjectNode()
        .put("Id", "123456")
        .put("Name", "the-container")
        .put("Path", "/foo/bar");
    final ContainerInfo info = mapper.treeToValue(objectNode, ContainerInfo.class);

    System.out.println(mapper.writeValueAsString(info));
  }
}
```

output:
```
{"Id":"123456","Created":null,"Path":"/foo/bar","Args":null,"Config":null,"HostConfig":null,"State":null,"Image":null,"NetworkSettings":null,"ResolvConfPath":null,"HostnamePath":null,"HostsPath":null,"Name":"the-container","Driver":null,"ExecDriver":null,"ProcessLabel":null,"MountLabel":null,"Volumes":null,"VolumesRW":null}

```

**Comment by stream1984** [comment]
Wow, thanks :+1:
