### ISSUE TITLE
Link multiple containers

### ISSUE THREAD

**Issue by jbrisbin** [spotify/docker-client#418]
I'm trying to start a cluster of software that requires multiple containers to communicate with one another. In other API clients I would just link two containers but I don't see that option in the Spotify client.

Is there a way I can achieve this with the Spotify client? If not, it's a deal-breaker for me and I'll have to revert to some other client but that would make me sad because I really like the API here better than the others.

**Comment by sayarg** [comment]
Which way are you trying to link?

**Comment by hazeltroost** [comment]
I'd like to know the same thing. I want to link a selenium node to a selenium hub.

**Comment by tdomzal** [comment]
It's definitely possible because I'm doing it in my testing library. 
You should use something like (written ad-hoc here so code will not compile probably but shows the idea). 

```
    HostConfig host1Config = HostConfig.builder()
        // host1 options...
        .build();
    ContainerConfig container1Config = ContainerConfig.builder().hostConfig(host1Config)
        // container1 options...
        .build();
    ContainerCreation container1 = dockerClient.createContainer(container1Config, "selenium-hub");
    dockerClient.startContainer(container1.id());

    HostConfig hostConfig2 = HostConfig.builder()
        // host2 options...
        .links("selenium-hub:hub")
        .build();
    ContainerConfig containerConfig2 = ContainerConfig.builder().hostConfig(host2Config)
        // container2 options...
        .build();
    ContainerCreation container2 = dockerClient.createContainer(container2Config);
    dockerClient.startContainer(container2.id());
```

So the trick is to create named container first and link to it from second container HostConfig options.

For working code example - see:
https://github.com/tdomzal/junit-docker-rule/blob/master/src/main/java/pl/domzal/junit/docker/rule/DockerRule.java#L109

**Comment by mattnworb** [comment]
Going to close this as it seems like @tdomzal has provided a working example.
