### ISSUE TITLE
Attached exec

### ISSUE THREAD

**Issue by sayarg** [spotify/docker-client#432]
## Description

Is there a away to run exec with attached dedicated connection / thread? Specifically how can this be done with passing InputStream for interacting with the exec? I see the execCreate can take attachStdin as an ExecCreateParam, but couldn't find a way to actually provide an InputStream to write into the exec.

My use case is to exec /bin/bash into a running container and then send commands via the InputStream, receive feedback via the OutputStreams provided to the log attach function.

**Comment by sayarg** [comment]
hey @mattnworb @davidxia any hints? is it possible with current support or otherwise happy to get it a go and submit a PR.

**Comment by rgrunber** [comment]
This has been asked before in the past, and I've generally linked people to Issue #156, where I describe an approach taken to do just that.

The problem is that Apache HttpClient doesn't support this so you only get back an Inputstream despite the fact that the underlying representation supports writing as well.
