### ISSUE TITLE
docker.load() seems to strip off metadata

### ISSUE THREAD

**Issue by talademo** [spotify/docker-client#464]
I am using Docker 1.10.2 and Spotify 5.0.2
When I load an image tarball using docker.load() it succeeds. However, when I look at the meta data (Labels, Config) using "docker inspect <image-name>" via CLI, the metadata is missing (Labels are lost, ...)

Does anyone see similar issues?

**Comment by johnflavin** [comment]
I think you’re running into a part of this library that is not fully implemented and—in my opinion—is confusingly named.

It seems you’re trying to use the [`/images/load` docker API endpoint](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#load-a-tarball-with-a-set-of-images-and-tags-into-docker). The method `DefaultDockerClient.load()` does not wrap `/images/load` endpoint, as the name would imply. Instead, it wraps the [`/images/create?fromSrc=-` docker API endpoint](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-an-image). The two endpoints are similar, but, as you've seen, they aren't the same. The key difference is that `/images/load` creates all the image layers contained in the tarball along with all the metadata, whereas `/images/create` makes a single image from the combined contents or the tarball. ...I think.

This issue was also brought up in #154, which is currently closed—erroneously, in my opinion.

I'll eventually get around to implementing `/images/load` in my huge 1.18 API PR #427, but I've not been progressing particularly quickly. It would get done a lot faster if you or someone else could make a smaller PR just focusing on this issue.

**Comment by davidxia** [comment]
Fixed by #494
