### ISSUE TITLE
Question -> docker run --rm

### ISSUE THREAD

**Issue by diemol** [spotify/docker-client#488]
## Description

Hi, 

When using the command line, I start the container like this: "docker run --rm {other options}...".

So far, I am able to start the container without any issues through the docker client, nevertheless I have not found how to add the "-- rm" option.

I saw this [issue](https://github.com/spotify/docker-client/pull/220), but I don't know if it is related to what I want to achieve.

If the option does not exist yet, I could implement it via PR. I just wonder if the [HostConfig](https://github.com/spotify/docker-client/blob/v5.0.2/src/main/java/com/spotify/docker/client/messages/HostConfig.java) class is the right place to do it. 
I see that most of the HostConfig parameters seen [here](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.25/#/create-a-container) are mapped in that class.

Please let me know if it is possible to add the option with an existing method or if I could go ahead and implement it.

Thanks!

**Comment by johnflavin** [comment]
I looked through the docker documentation, and I couldn't find a way to do it. You can check for yourself: https://github.com/docker/docker/tree/master/docs/reference/api. 

If there is no documentation on how to do it, then either
1. There is no way, it doesn't exist.
2. There is a way, but it isn't documented.

I strongly suspect that 2 is the more likely option. In that case, you could open an issue with docker/docker to document the API for the `--rm` option. Once they document that, we'll know where to add the option on this side, and maybe you could do a PR for that.

**Comment by diemol** [comment]
I read again the link I provided for the docker API doc, and the field is there, it is called `AutoRemove`.
The thing is that it is added in the version 1.25 which has not been released (I think).
So, I guess we just need to wait until the new API version is released.

**Comment by johnflavin** [comment]
Yes, it does appear that `HostConfig.AutoRemove` was added in docker/docker#20848, and will be released in API 1.25. It looks like, in all existing docker versions, `--rm` is a bit of client-side trickery that removes the container when the client detects that it has died. Since the client was responsible, there was no daemon API to make it happen. Now with the newer version they moved that function to the daemon, thus it can be exposed through the API.

I think you could add that field to the `HostConfig` class before the Docker version is released without harming anything. You could even add tests for it, wrapped in a conditional `if(apiVersionAtLeast("1.25")) {}` or whatever the helper method is.

**Comment by diemol** [comment]
Great, I will add it and send the PR around next week. 
Thanks.

**Comment by diemol** [comment]
PR sent https://github.com/spotify/docker-client/pull/526

**Comment by davidxia** [comment]
Closed by https://github.com/spotify/docker-client/pull/538
