### ISSUE TITLE
change in DockerException message between docker 1.10.3 and 1.12.1

### ISSUE THREAD

**Issue by jjohnstn** [spotify/docker-client#507]
## Description

The Linux Tools project which ships the docker-client as part of its Docker Tooling plug-ins has a user scenario where an attempt is made to tag an image with an upper-case repo.  Using 1.10.3, a DockerException is thrown which has the following getMessage() response:

invalid reference format: repository name must be lowercase

This is fine.  When the same scenario and plug-ins are used with upstream docker 1.12.1, the message comes back as:

{'message' : 'invalid reference format: repository name must be lowercase'}

Is this a bug with the upstream daemon or has the message format changed and docker-client/Docker Tooling is not prepared for it?
## How to reproduce

Try and tag an image with FEDORA:myFEDORA.
Catch the exception and display e.getMessage().
## What do you expect

See description.
## What happened instead

See description.
## Software:
- `docker version`:  1.12.1
- Spotify's docker-client version: 4.0.6
## Full backtrace

``` text
[Paste full backtrace here]
```

**Comment by johnflavin** [comment]
This is a new behavior in Docker 1.12.0 and up, introduced in docker/docker#22880. `docker-client` has not yet been updated to correctly process the JSON error messages.

**Comment by johnflavin** [comment]
For clarification: is this breaking anything for you, or was it just not what you expected to see?

**Comment by jjohnstn** [comment]
It is a UI bug filed by an end-user, but no, there is no breakage.  The message is displayed in a dialog.  I would prefer not to hack our dialogs that display exceptions to look for such a message format.  If the issue is fixed in a later version of docker-client, then we will simply move to that version.  If the bug is on docker's side, I would like to open a bug to have it fixed in the future.

**Comment by johnflavin** [comment]
I would not call this a docker "bug". For them, it is a new feature. It was an intentional change. It makes their API more consistent in that everything returns JSON.

You might call it a "bug" in docker-client; we aren't doing anything to parse the structure of the error message. It seems a little closer to a feature request than a bug, though. But I may be making a distinction without a difference. 

I think the most likely outcome is that docker-client will be updated—hopefully soon—to parse the error message. That future version will restore the behavior you expect.

**Comment by jjohnstn** [comment]
Thanks for the explanation.  I guess we can put in a temporary parser to look for this until then.
