### ISSUE TITLE
docker events

### ISSUE THREAD

**Issue by olegtikhonov** [spotify/docker-client#555]
## Description

Seems that system events, like swarm create networks, is not parsed well.

## How to reproduce

Just after installing docker 1.13 rc #4, create swarm, add one manager. Get events.

## What do you expect

As an usual Event with id, status, timestamp and from.
```text
bash-4.2$ docker events --until 1s
2016-12-22T16:00:55.003985718+02:00 network create lwk7weztsil3vvwjnch6sgjc4 (name=ingress, type=overlay)
```

## What happened instead

```
Event{status=null, id=null, from=null, time=Thu Dec 22 16:00:55 IST 2016}
```
## Software:

- `docker version`: Docker version 1.13.0-rc4, build 88862e7
- Spotify's `docker-client version`: 6.1.1

## Full backtrace

```java
 try {
            EventStream es = dockerClient.events(EventsParam.since(new Date().getTime() / 100));
            
            Callable<List<Event>> callableObj = new Callable<List<Event>>() {
            	@Override
                public List<Event> call() throws Exception {
                    while (es.hasNext()) {
                        Event event = es.next();
                        events.add(event);
                        if (event.status() != null) {
                            log.info(event.id() + ", " + event.status() + ", " + event.time() + ", " + event.from());
                        }
                    }
                    return events;
                }
            };
           
            ExecutorService service =  Executors.newSingleThreadExecutor();
            Future<List<Event>> future = service.submit(callableObj);
            
            // Delay of two seconds.
            List<Event> result = future.get(2, TimeUnit.SECONDS);  
            events.stream().forEach(log::info);
            
            return result;
           
        } catch (Exception e) {
        	events.stream().forEach(log::info);
        	return events;
        }
```

**Comment by johnflavin** [comment]
Yes, the Docker Events API has been updated a lot since `docker-client` added support. The fields that `docker-client` parses—`status`, `id`, `from`, and `time`—are almost all deprecated. The older types of events—image and container—will still have values in those fields, even though the fields are redundant in the newer Event model. But newer events—network and service/swarm—do not have any values in the legacy fields.

I have a PR open (#754) to update the Event model objects in `docker-client`, but I've neglected it. Let me polish that up, rebase it, see why one of the tests failed, etc.

**Comment by davidxia** [comment]
@olegtikhonov 6.2.5 has PR #549. Does it work for you?

**Comment by olegtikhonov** [comment]
Sorry for delay. Going to try. Will keep updated.

**Comment by olegtikhonov** [comment]
@davidxia 
thumbs up !!! Perfect. Thanks guys !!!!
