### ISSUE TITLE
Unable to list servies in docker 1.13

### ISSUE THREAD

**Issue by michaelkrog** [spotify/docker-client#607]
## Description

When listing service using `DockerClient.listServices()` an Exception occurs.

## How to reproduce

1. install Docker 1.13
2. Init swarm `docker init swarm`
3. Create service fx. `docker service create --name nginx nginx``
4. List services via DockerClient `
dockerClient.listServices()`

## What do you expect

I would expect a list returned containing the service running in Docker swarm.

## What happened instead

An exception occurs.

## Software:

- `docker version`: 1.13.0 / 1.13.0
- Spotify's docker-client version: 7.0.2

## Full backtrace

```
javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.swarm.ContainerSpec, problem: null  at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@11c54539; line: 1, column: 332] (through reference chain: java.util.ArrayList[0]->com.spotify.docker.client.messages.swarm.Service["Spec"]->com.spotify.docker.client.messages.swarm.ServiceSpec["TaskTemplate"]->com.spotify.docker.client.messages.swarm.TaskSpec["ContainerSpec"])
````

Inspecting via CLI gives this result:
```
$ docker service inspect nginx
[
    {
        "ID": "l7vbbqjudq2fzpxa8jfskp0b6",
        "Version": {
            "Index": 10347
        },
        "CreatedAt": "2017-02-02T09:40:53.040279473Z",
        "UpdatedAt": "2017-02-02T09:40:53.040279473Z",
        "Spec": {
            "Name": "nginx",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:latest@sha256:f2d384a6ca8ada733df555be3edc427f2e5f285ebf468aae940843de8cf74645",
                    "DNSConfig": {}
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {},
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "MaxFailureRatio": 0
            },
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {}
        },
        "UpdateStatus": {
            "StartedAt": "0001-01-01T00:00:00Z",
            "CompletedAt": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by johnflavin** [comment]
This sounds like it has a similar cause to #604: when the message classes were converted over to `AutoValue` all the fields had to be explicitly annotated as `@Nullable` if they were to handle null values, but some weren't. I can't check the code right now, but I suspect that is the problem here.

**Comment by johnflavin** [comment]
I may have been wrong in my last comment 👆. But I'm not sure because I'm confused.

The error indicates that the problem is deserializing a `null` value, and if you look all the way at the end it seems to be either a `null` `ContainerSpec` or a `null` inside `ContainerSpec`. Neither of those make sense to me as the cause of the error:
* In the example you posted that gets returned from the CLI, the `ContainerSpec` is not `null`. So why would there be a `null` `ContainerSpec` returned from the API? (This could indicate a mismatch between what you asked docker through `docker-client` and what you asked on the command-line.)
* All of the fields in `ContainerSpec` are marked `@Nullable` (except for `"Image"`, which I guess makes sense). So throwing a `null` into any of them shouldn't cause a problem.
* Our `ContainerSpec` class does not have the field `DNSSpec` that your `ContainerSpec` message does have. So that might cause a problem. But I wouldn't think so, because A. we have jackson set to ignore fields it does not know about, and B. the error does not say "I have this extra field I don't know what to do with", it says the problem is a `null` field.

I haven't yet tried to reproduce. Maybe if I did that I would be able to discern more.

@davidxia Care to take a 👀 ?

**Comment by johnflavin** [comment]
I had overlooked `ContainerSpec.command`. It was not annotated with `@Nullable`, and is not present in your example. I bet that is the true source of this error.
