### ISSUE TITLE
error=unauthorized: authentication required

### ISSUE THREAD

**Issue by sinkiangscorpio** [spotify/docker-client#628]
## Description

[My Docker machine ip is 192.168.99.100,
when I access this ip by telnet and push a mirror to REPOSITORY，
prompt:
unauthorized: authentication required

so I add a file in  a dir that is /home/docker/.docker/config.json at My Docker machine
This config.json file's content is:
{
  "auths": {
    "xxx.xxx.xxx.xxx:xxxxx": {
      "auth": "ZGVmYXVsdEBJS1JORlRYMU9KTTVaQ0lVSDRTUDpmNWEzM2VjNWMwNmYwYjdlYTE4ZjE2YThlMTU2YTljNDJjN2JlODYxM2YxZjVhOTQ1NzQ4MjM4NGYzOWRiZWE4"
    }
  }
}
now I can push a mirror successful.

but I run a program eg：
docker = DefaultDockerClient.builder()
			        .uri(DOCKER_HOST)
			        .dockerCertificates(new DockerCertificates(Paths.get(DOCKER_CERT_PATH)))
			        .readTimeoutMillis(120000)
			        .build();

final String name = "xxx.xxx.xxx.xxx:xxxxx/xxx/xxx:1.0";
docker.push(name);

prompt:
com.spotify.docker.client.exceptions.ImagePushFailedException: Image push failed: xxx.xxx.xxx.xxx:xxxxx/xxx/xxx:1.0: ProgressMessage{id=null, status=null, stream=null, error=unauthorized: authentication required, progress=null, progressDetail=null}
	at com.spotify.docker.client.LoggingPushHandler.progress(LoggingPushHandler.java:43)

But My Docker machine's StorePath is "C:\\Users\\admin\\.docker\\machine\\machines\\default",
Under this directory There is a same name file config.json.
this file's content is:
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.99.100",
        "MachineName": "default",
        "SSHUser": "docker",
        "SSHPort": 50520,
        "SSHKeyPath": "C:\\Users\\admin\\.docker\\machine\\machines\\default\\id_rsa",
        "StorePath": "C:\\Users\\admin\\.docker\\machine",
.........................
 So How do I push a docker mirror and avoid this error by programe successful?]

## What do you expect

[I expect to push a docker machine successful]

## What happened instead

[com.spotify.docker.client.exceptions.ImagePushFailedException: Image push failed: 192.168.68.12:30303/adtec_starring/staringtest:6.0: ProgressMessage{id=null, status=null, stream=null, error=unauthorized: authentication required, progress=null, progressDetail=null}
	at com.spotify.docker.client.LoggingPushHandler.progress(LoggingPushHandler.java:43)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:74)
	at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1204)
	at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1182)
	at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1170)
	at DockerTest.create(DockerTest.java:125)
	at DockerTest.main(DockerTest.java:34)]

## Software:

docker@default:~/.ssh$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Comment by johnflavin** [comment]
It looks like docker-client can't read your config file, because it is on the machine where docker is running, not the machine where docker-client is running. So you either need to have that config file on the machine where docker-client is running, or you can explicitly construct the `RegistryAuth` object yourself:
```java
final RegistryAuth registryAuth = RegistryAuth.builder()
            .username("your username")
            .password("your password")
            .serverAddress("probably https://index.docker.io/v1/")
            .build();
final DockerClient client = DefaultDockerClient.builder()
            .registryAuth(registryAuth)
            .build()
````

**Comment by sinkiangscorpio** [comment]
The machine where docker-client is running also have a config.json,I cann't overwrite this file.
how can I move  or modify this file?

**Comment by johnflavin** [comment]
If you use the [docker login](https://docs.docker.com/engine/reference/commandline/login/) command, docker saves the credentials you give it in the `config.json` file. 

But before you do that, you should know how `RegistryAuth` uses that file. Because depending on your situation you may or may not be able to use that file.
* If you get a `RegistryAuth` instance from the `config.json` by using `RegistryAuth.fromDockerConfig()` or `RegistryAuth.fromDockerConfig(Path configPath)`, then it will always use the first set of credentials that it finds. Since you will be adding your credentials into an already existing file they will not be the first and these methods will never select your credentials.
* If the URL of the registry you are authenticating to (what you called `"xxx.xxx.xxx.xxx:xxxxx"` in your original post) is *different* from the other credentials in the file, then you will be able to use `RegistryAuth.fromDockerConfig("xxx.xxx.xxx.xxx:xxxxx")` or `RegistryAuth.fromDockerConfig(Path configPath, "xxx.xxx.xxx.xxx:xxxxx")` to get a `RegistryAuth` instance with the correct credentials.

If the server to which you’re authenticating is the same as someone else's who is already in the `config.json` file, then you’re pretty limited. You could instantiate a `RegistryAuth` by hand, as I outlined in my [previous comment](https://github.com/spotify/docker-client/issues/628#issuecomment-280373652). 

If you are willing to, you could always submit a PR to make the code do what you need to do. You could write some new static method `RegistryAuth.fromDockerConfigWithUsername(String username)` that would look through all the entries in the `config.json` file and return the one with the specified username.

**Comment by mattnworb** [comment]
should be improved by #740, although it won't solve the issue where the docker client config file is on a different machine than where your JVM runs.

**Comment by mattnworb** [comment]
I am going to close this as I think that the underlying issue is that you have different authentication info in the config file on the machine where you run docker-client versus the machine where the docker daemon lives. My suggestion would be to find a way to get the latter info into the code that is using docker-client, using one of the methods that @johnflavin outlined.
