### ISSUE TITLE
pulling an image from private repository always needs authentication

### ISSUE THREAD

**Issue by grexe** [spotify/docker-client#682]
When pulling an image from my private local repository using e.g.
`dockerClient.pull("my.local.repo/image:version")`
I always get an error that the image cannot be found, even when I have previously built the dockerClient with authentication info (so it is not reused).

However, when adding the `AuthRequest` info to the pull call again, it works!
Digging through the code, I see that when I don't pass any auth info, the default auth info for the global Docker registry is used, which of course fails for my private local repo!

Why do I need to specify authentication info at all, when my local docker daemon already IS authenticated against the local registry?
I'd rather not add dependencies to certificates and username/password info when not needed.
My colleague is using a Python lib that does not need authentication in the same use case.

I'd prefer the docker library to hand over to the docker daemon directly for pulling an image instead of accessing the registry API.

Docker version 1.12.6, build 78d1802
Docker Java Lib: 8.1.2
Java 8, Ubuntu Linux x64 16.10

**Comment by grexe** [comment]
on a related note, `searchImage()` does not work in this context, and cannot be fixed, since it does not have a variant that accepts a `RegistryAuth`, so the default Docker login info is used, which of course fails for my local private registry.

**Comment by johnflavin** [comment]
How are you building your `DockerClient` instance?

It looks like you can set the `RegistryAuth` value on the builder using `DefaultDockerClient.builder().registryAuth(RegistryAuth)`. However, whatever you set there [gets overwritten](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L2433) by the default when building if you also set `builder.dockerAuth(true)`. (That seems like a bug we should fix. Maybe that check should be `if (registryAuth == null)`, and `boolean dockerAuth` should be deprecated.) 

The `RegistryAuth` that you set on the `Builder` should be kept on the `DockerClient` instance if you set `builder.dockerAuth(false)`.

**Comment by grexe** [comment]
thanks @johnflavin for the always quick response!
Can confirm that building the client correctly with:
`DefaultDockerClient.fromEnv().dockerAuth(false).registryAuth(registryAuth).build();`
works and does not override the auth.

For search there seems to be no solution though;(

**Comment by johnflavin** [comment]
And a few quibbles with your issue report:
* docker-client does not access any registry API directly. We always use the docker daemon APIs, which communicate with the registry on our behalf. (Which is good for everyone, because the registry APIs are sparsely documented.)
* docker-client could maybe be smarter about how it authenticates. Rather than setting a single `RegistryConfig` on a  `DockerClient` instance, one could be constructed for you when you pull based on the format of the string you pass in. But I hesitate to do that. Getting the auth details on your behalf involves manually parsing docker's config json file, in which your username and password are stored in (essentially) plain text. We already have code that does that, but it makes me uncomfortable. And very soon that will stop working anyway; see #657.

**Comment by johnflavin** [comment]
It looks like `DefaultDockerClient#imageSearch` does not use the `registryAuth`. However, I think that is because docker's API documentation does not mention that this endpoint needs any authentication.

When you do a `docker search` on the command line, does it search your registry? Do you need to tell it what registry to search, and if so how?

**Comment by grexe** [comment]
thanks for the quibbles,-)
ad 1) So afaik the Python library uses direct socket/tcp access to the daemon as opposed to the REST API that this libary uses, which seems to cause the different authentication requirements (makes sense that the REST API is secured and requires client authentication after all).

ad 2) no I wouldn't do that, either. Now that I know why and how to correctly construct the client, I'm fine with the current way it works.

re image search: yes this is sadly not possible, as noted in my comment above, I also found no way to specify a registry (authentication) in the Engine REST API docs, which is unfortunate.

I'd like to search all tags for a given image, maybe there's another way to get this?

**Comment by johnflavin** [comment]
This library can also communicate with docker using the socket. It's the default, in fact. And both the socket and tcp connections use docker's REST API. I suspect docker-client and the python library you're talking about do pretty much the same thing, aside from some minor bugs or missing features.

**Comment by grexe** [comment]
have to clarify what the Python lib does differently, but interesting to know that even going over socket uses the REST API in the end?
Anyway thanks for the info, I'll have to ask the Docker team for the search-in-registry feature and close this now.
