### ISSUE TITLE
Support --follow-link on archiveContainer (docker cp)

### ISSUE THREAD

**Issue by elgalu** [spotify/docker-client#720]
## Description

Add support for `--follow-link` option on `archiveContainer` / [copyToContainer](https://github.com/spotify/docker-client/blob/0a4a646d0fa37f1d65cce3a0c0adc9631f181403/src/main/java/com/spotify/docker/client/DockerClient.java#L1183) i.e. in `docker cp`:
https://docs.docker.com/engine/reference/commandline/cp/

**Comment by johnflavin** [comment]
I looked through docker's API documentation (which you can see in an [HTML version](https://docs.docker.com/engine/api/v1.27/), or [swagger.yaml](https://github.com/docker/docker/blob/master/api/swagger.yaml)), and I don't see that option anywhere. That could mean one of two things: that option does exist in their API but it isn't documented, or it doesn't exist in their API. If it is in their API, and they document it, then we can add it here. But if it isn't in their API, we can't use it. 

I think it is most likely that it just isn't documented yet. Could you open an issue with [docker](http://github.com/docker/docker) about this?

**Comment by johnflavin** [comment]
To summarize docker/docker#32535, the `--no-follow` flag on `docker cp` is implemented on the client side, not the daemon side. So to get that feature in `docker-client`, the functionality has to be re-implemented here rather than just poking some docker REST API.

If you’re up for it @elgalu, this would make a good PR. It's certainly doable, but it will require more effort to implement and more testing to validate than the typical "support the foo docker API" PR.

**Comment by elgalu** [comment]
I see. I won't be working on this so feel free to close or tag. Thanks for your time!!
