### ISSUE TITLE
[question] Container bound to custom network

### ISSUE THREAD

**Issue by mariotoffia** [spotify/docker-client#746]
## Description
Hi, I wonder how to create a container that gets assigned an IP address within a custom network much like the `docker run --network nw ...` does. 

I can successfully attach a container to a network and thus gets two interfaces one in the _default_ bridge network and one in the custom network. But I don't understand how to create a container that _only_ has a network address inside the custom network and not in the _default bridge.

I've seen that a `NetworkingConfig` exists inside the `ContainerConfig`. Is this the one I should use and add a `EndpointConfig`. I'm really in "high water" here.

Cheers,
 Mario

**Comment by johnflavin** [comment]
I'm not sure exactly how to get that to work. I am familiar with most parts of the docker API, but networking is not one of my strengths. 

The heart of your question is not really about `docker-client`, it is about the docker API. You know how to do something on the command line, but now you need to translate that into API objects and it is not clear how. But once you figure out how to get docker to do what you want by using the API, then it should be straightforward to get `docker-client` to do that same thing, since `docker-client` mostly reflects the docker API very closely. With that in mind, I think that this question may be better suited for the [docker forums](https://forums.docker.com) or [stack overflow](http://stackoverflow.com/search?tab=newest&q=docker). Phrase your question there in terms of getting the docker API to do something and I think you will get the answer you need.

(I don't want to discourage you from asking questions here. I am happy to help! But I don't know how to answer this particular question, and I think there are other people elsewhere who do.)

**Comment by mariotoffia** [comment]
@johnflavin Hi and thanks for the prompt response.

Sorry for asking a question here - will not do it again.

I solved it as you said, just checking on the protocol level and spotted the `HostConfig.networkMode` which you have in the builder as well.
