### ISSUE TITLE
How to delete the half baked image

### ISSUE THREAD

**Issue by vaibhavswarnkar** [spotify/docker-client#874]
While creating an image from Dockerfile, how to remove the half build image from the images list if the build fails? 

I have a requirement where if an image build fails, I want to delete all of the layers which were created during the build. I can see these images in my docker instance with `<none>` in `repository` and `tag` column after typing `docker images` command.

I am trying to delete the image but, since on error, you don't get any ID of the image, I am not able to do so. 

Below is the code I am using to achieve the same.

```java

        final AtomicReference<String> imageIdFromMessage = new AtomicReference<>();
        final AtomicReference<String> errorAtomicReference = new AtomicReference<>();
String buildId = dockerClient.build(Paths.get(filePath), name, new ProgressHandler() {
            @Override
            public void progress(ProgressMessage progressMessage) throws DockerException {
                String id = progressMessage.buildImageId();
                String error = progressMessage.error();
                if (id != null) {
                    imageIdFromMessage.set(id);
                }
                if (error != null) {
                    errorAtomicReference.set(error);
                }
            }
        });

        String error = errorAtomicReference.get();
        String imageId = imageIdFromMessage.get();
        if (error != null) {
            dockerClient.removeImage(buildId, true, false);
        } else {
            dockerClient.tag(name, tag, true);
            dockerClient.push(tag);

            dockerClient.removeImage(imageId, true, false);
            dockerClient.removeImage(buildId, true, false);
        }

**Comment by davidxia** [comment]
@vaibhavswarnkar `ProgressMessage.buildImageId()` is non null when the image has been built successfully. Each `ProgressMessage` instance is essentially a line from docker daemon's stdout. So for a Dockerfile like

```
FROM busybox
RUN echo hi
RUN foo.sh
CMD ["/date.sh"]
```

There will be multiple `ProgressMessage`s with `stream()`s or `error()`s that correspond to lines below.

```
Step 1/4 : FROM busybox
 ---> 6ad733544a63
Step 2/4 : RUN echo hi
 ---> Using cache
 ---> 39c467755fa7
Step 3/4 : RUN foo.sh
 ---> Running in d35df0821d95
/bin/sh: foo.sh: not found
The command '/bin/sh -c foo.sh' returned a non-zero code: 127
```

Getting the intermediate image IDs will require parsing the output and recognizing lines like ` ---> 39c467755fa7` are intermediate containers that can be deleted. The first one shouldn't because it's the image ID of busybox.

We're probably not going to provide this functionality because this library is focused on interacting with the Docker Remote API. You can probably script something with `docker rmi` or use other methods in this library to detect which images don't have names or tags and delete them.
