### ISSUE TITLE
Document how to connect a container to a network before it is started

### ISSUE THREAD

**Issue by cowwoc** [spotify/docker-client#911]
## Description

I'm trying to invoke `docker create --network mynetwork` using the API. I found `DockerClient.createContainer(ContainerConfig.builder().networkingConfig(...))` but I don't understand how to express the command-line in terms of this API.

## Software:

- `docker version`: Docker version 17.09.0-ce, build afdb6d4
- Spotify's docker-client version: 8.9.1

**Comment by testphreak** [comment]
It appears from your command above that you are creating a container. You should be using the createNetwork method instead. Your best bet is to read the JavaDoc instead of the user manual as it doesn't appear to have been updated with the newer Docker APIs.

To learn about how to create a network with the docker-client, you can either download the sources to read the JavaDoc or go [here](https://static.javadoc.io/com.spotify/docker-client/8.9.1/com/spotify/docker/client/DefaultDockerClient.html#createNetwork-com.spotify.docker.client.messages.NetworkConfig-).

**Comment by cowwoc** [comment]
@testphreak I think I am misunderstanding you, or you are misunderstanding me.

I'm not asking how to create a new network. I already used `createNetwork` to that end.

I'm asking how to create a container inside an existing network. Meaning, after `createNetwork` has been invoked, how I create a new container and add the container into that network?

`docker create --network myNetwork` where `myNetwork` already exists does that. It's just not clear how to do the same using this API.

**Comment by cowwoc** [comment]
I think I figured out how to do this. I need to invoke `DockerClient.createContainer()` followed by `DockerClient.connectToNetwork()`. Can you please add this example to the Wiki documentation?

**Comment by cowwoc** [comment]
If I `DockerClient.connectToNetwork()` before `DockerClient.startContainer` then sometimes `connectToNetwork()` fails silently. If I run it after starting the container, it seems to work, but I'm afraid this approach is open to race-conditions (the container might need to use the network before it gets connected).

How can one reliably connect a container to a network prior to starting it?

**Comment by cowwoc** [comment]
Sorry for all the chatter but I discovered something else.

The reason `connectToNetwork()` was failing silently was because I had multiple networks with the same name. The reason I had multiple networks with the same name was that `DockerClient.createNetwork().checkDuplicate()` is false by default. See https://github.com/moby/moby/issues/18864 for a related discussion.

**Comment by sathipal** [comment]
Hi, is there a way to specify --network-alias using this library?

**Comment by shpendk** [comment]
i'd also be interested in knowing how to specify an alias

**Comment by lannierose** [comment]
I just spent a long time working on this one, and here is my solution. I am creating a new container to connect to an existing network named  docker_elastic. In the body (curl -d) of the create API request, add a NetworkingConfig like this: "NetworkingConfig": { "EndpointsConfig": { "docker_elastic": {} } }. What was so confusing is that the documentation says "<Additional Properties>*" and doesn't explain what that means, and the example uses "isolated_nw" without explaining that it gets replaced with the name of your network. The value of my network is an empty object because the network already exists, and Docker will pick up the IP addresses and so on from that.
