### ISSUE TITLE
Shouldn't maven dependency download all the packages and classes?

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [spotify/docker-client#924]
## Hello. I set the pom xml as described here.
I am trying to make a software to deal with docker swarm but the 
swarm package has been not downloaded. What is wrong?

![here, you can see that the package swarm is not there](https://user-images.githubusercontent.com/4364432/32778434-a19e4eb0-c918-11e7-876f-3c12039f0ecd.png)
my pom.xml is like this

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>br.ufpe.cin.gfads</groupId>
	<artifactId>swarm-runtime</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<dependencies>
		<dependency>
			<groupId>com.spotify</groupId>
			<artifactId>docker-client</artifactId>
			<version>3.5.12</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.5</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.5</version>
		</dependency>
	</dependencies>
</project>
```

**Comment by mattnworb** [comment]
Hi, in the future please copy and paste the text of an error message you get, so that people with the same problem as you can find this issue when searching. Screenshots can’t be searched and are hard to interpret as to what problem you are having. I’m not sure what problem the second screenshot is supposed to show, can you please describe more what you expect to happen and what you are seeing instead?

The 3.5 version of docker-client is old and I think predates any Swarm-related classes. The latest version is 8.9 I believe.

**Comment by ViniciusDeAndrade** [comment]
sorry.
Yeah, I already fixed it. Just by using the 8.9.1 version on the pom.xml.
I do not know what was wrong, but it was an error in this version tag:
`
<version>LATEST-VERSION</version>`

That tag above did not work properly
