### ISSUE TITLE
how to copy file from file system into running container

### ISSUE THREAD

**Issue by olegtikhonov** [spotify/docker-client#943]
## Description
I would like to find a way how to copy a file from file system into running container
## How to reproduce
```
Path path2Script = PulseUtils.getResource("mariadb_dump.sh");
DefaultDockerClient dockerClient = DefaultDockerClient.fromEnv().build();
dockerClient.copyToContainer(path2Script, "009ac05436f4", "/tmp/");
```
## What do you expect
A way to do it.
## What happened instead
```
com.spotify.docker.client.exceptions.DockerRequestException: Request error: PUT unix://localhost:80/containers/009ac05436f4/archive?noOverwriteDirNonDir=true&path=%2Ftmp%2F: 500, body: {"message":"Error processing tar file(exit status 1): cannot overwrite directory \"/\" with non-directory \"/\""}
```
## Software:

- Client:
``` 
Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64
```
- Server:
``` 
Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
- Spotify's docker-client version:
```
8.10.0
```

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by johnflavin** [comment]
I know this isn't a problem with `copyToContainer` generally; there are several tests that check it. Something about how you have things set up must be causing some problem. But there isn't enough in your "How to reproduce" section for me to actually reproduce what you are seeing. 

Could you provide something more self-contained—ideally a working test—that would allow us to reproduce this?

**Comment by olegtikhonov** [comment]
Agree. I do something else. I take your unit test(s) and try out. Thanks for response.

**Comment by olegtikhonov** [comment]
Here is a test where a problem can be reproduced
`  @Test
  public void testCopyToContainer() throws Exception {
      requireDockerApiVersionAtLeast("1.20", "copyToContainer");

      // Pull image
      sut.pull(BUSYBOX_LATEST);

      // Create container
      final ContainerConfig config = ContainerConfig.builder().image(BUSYBOX_LATEST).build();
      final String name = randomName();
      final ContainerCreation creation = sut.createContainer(config, name);
      final String containerId = creation.id();

      //    final Path dockerDirectory = getResource("dockerSslDirectory");
      final Path dockerDirectory = getResource("logback-test.xml");
      try {
          sut.copyToContainer(dockerDirectory, containerId, "/tmp");
      } catch (Exception e) {
          fail("error to copy files to container");
      }
  }`

**Comment by johnflavin** [comment]
Ok, now I see what is happening. I can reproduce your issue.

To restate what I see happening:
* The existing test `DefaultDockerClientTest.testCopyToContainer()` copies a directory to a container.
* You can modify that test to copy a file instead of a directory, and it gets an exception.
* To confirm the exception you got, I added a line inside the catch block which logs the exception: `log.error("ERROR", e);`. I got

```
com.spotify.docker.client.exceptions.DockerRequestException: Request error: PUT unix://localhost:80/containers/<containerId>/archive?noOverwriteDirNonDir=true&path=%2Ftmp: 500, body: {"message":"Error processing tar file(exit status 1): cannot overwrite directory \"/\" with non-directory \"/\""}
```

I'll dig a little deeper to investigate.

I can use the `docker` CLI to do this. I copy a file into a container (which is created, but not started), then copy it back out.
```bash
$ f=<some file in my pwd>
$ container=$(docker create busybox:latest)
$ docker cp $f ${container}:/tmp
$ mv $f ${f}.old
$ docker cp ${container}:/tmp/${f} .
$ diff ${f} ${f}.old
$ echo $?
0
```
Seems to work fine.

I'm guessing this is the issue: https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L931
```java
@Override
  public void copyToContainer(final Path directory, String containerId, String path)
      throws DockerException, InterruptedException, IOException {
    final CompressedDirectory compressedDirectory = CompressedDirectory.create(directory);
    final InputStream fileStream = Files.newInputStream(compressedDirectory.file());
...
```
This method assumes what you are giving it is a directory. It compresses that directory into a tarball. Then, it passes that tarball stream to the next method: https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L938.
```java
@Override
public void copyToContainer(InputStream tarStream, String containerId, String path)
    throws DockerException, InterruptedException {
  final WebTarget resource = resource()
      .path("containers")
      .path(containerId)
      .path("archive")
      .queryParam("noOverwriteDirNonDir", true)
      .queryParam("path", path);

  try {
    request(PUT, String.class, resource,
            resource.request(APPLICATION_OCTET_STREAM_TYPE),
            Entity.entity(tarStream, "application/tar"));
  } catch (DockerRequestException e) {
    switch (e.status()) {
      case 400:
        throw new BadParamException(getQueryParamMap(resource), e);
      case 403:
        throw new PermissionException("Volume or container rootfs is marked as read-only.", e);
      case 404:
        throw new NotFoundException(
            String.format("Either container %s or path %s not found.", containerId, path), e);
      default:
        throw e;
    }
  }
}
```
This method takes any `InputStream`, but it assumes it is a tar stream and sets the header accordingly.

I can think of two ways this could be fixed.
1. In the `copyToContainer` that takes a `Path`, the input should be checked if it is a file or a directory. If it is a file it will likely need to be handled differently from a directory. 
2. In the `copyToContainer` that takes an `InputStream`, do not assume the stream is a tar stream. Pick some default encoding header, but let it be overridden by a parameter. (I don't know what the default encoding header should be, but I don't think it should be `application/tar`.) That way, at least you would be able to open the file as an input stream yourself and copy that to the container.

**Comment by rwmajor2** [comment]
Any fix to this?  I simply cannot figure out how to copy a single file to a container using copyToContainer().

**Comment by johnflavin** [comment]
This has not been fixed. It would not be too much work for whoever wants to take on the task.

The easiest fix, I think would be in `DefaultDockerClient.copyToContainer(Path, String, String)`. That method assumes the `Path` is to a directory, and compresses it as such. To fix that, one would need to check if the `Path` is a directory or not. If it is, make the directory into a tarball as is done right now. If not, write some new code to make the a tarball stream from the single file.
