### ISSUE TITLE
Is there any method to provide the already executed replicas value of services like docker CLI "docker service ls"

### ISSUE THREAD

**Issue by xiaohesdu** [spotify/docker-client#947]
## Description
I have just used the spotify docker client to create services in a swarm. Everything is OK,  and I want to check the execution state of all services to verify if the services are finally executed. I know that spotify provide the method  listServices() to provide the information of all services, but it can not provide the already executed replicas numbers of a service, whicn can be provide in docker CLI "docker service ls".

For example, the below picture is the debug info in IDEA, which shows  one service infomation given by listServices() method. I can just know the expected replicas value.
![idea](https://user-images.githubusercontent.com/31200855/33931031-cd499c68-e029-11e7-9536-5b93e47f9828.PNG)
 
And in the CLI, the result of  "docker service ls" command is shown below. Not only the expected value of replicas, but also the value in real state can be acquired.
![command](https://user-images.githubusercontent.com/31200855/33931329-a0ca9bb4-e02a-11e7-971f-ad6a62ac0e0e.PNG)

## How to reproduce

seen above

## What do you expect

Is there any method to acquire the already executed replicas value of services?
I think the listTasks() method can be useful, but it is sophisticated to realize the same function. 

## Software:

- `docker version`: docker 17.09
- Spotify's docker-client version: 8.9.0

## Full backtrace

```text

```

Thanks.

**Comment by johnflavin** [comment]
There is no easy way to do this, sorry. But I can explain why.

When you call `DockerClient.listServices()`, that gets translated into a call to the Docker API. Docker sends back a JSON list of services, and `docker-client` binds those into java `Services` objects. Here is an example of the JSON that gets sent back from the API:
```json
  {
    "ID": "za84hqdj0tvmskhc68q8yf7hk",
    "Version": {
      "Index": 54
    },
    "CreatedAt": "2017-10-31T15:49:46.658654787Z",
    "UpdatedAt": "2017-10-31T15:49:46.658654787Z",
    "Spec": {
      "Name": "suspicious_fermat",
      "Labels": {},
      "TaskTemplate": {
        "ContainerSpec": {
          "Image": "xnat/debug-command:latest",
          "Command": [
            "/bin/sh",
            "-c",
            "echo hello world > /output/out.txt"
          ],
          "Env": [
            "XNAT_USER=03dcbc11-21ee-489f-9eb6-ed796db23142",
            "XNAT_PASS=YPzaMZGyPiuk3mj11u3Blx72K9gozaXv4LkY1Y7dexZM43nbINPscdHZdMEKMRR3",
            "XNAT_HOST=http://xnat-31.xnat.org"
          ],
          "Mounts": [
            {
              "Type": "bind",
              "Source": "/data/xnat/archive/auto/arc001/5Yp0E/SCANS/801",
              "Target": "/input",
              "ReadOnly": true
            },
            {
              "Type": "bind",
              "Source": "/data/xnat/build/19f5bba1-7839-44a4-aef0-717fe8fb3650",
              "Target": "/output"
            }
          ]
        },
        "RestartPolicy": {
          "Condition": "none",
          "MaxAttempts": 0
        },
        "ForceUpdate": 0,
        "Runtime": "container"
      },
      "Mode": {
        "Replicated": {
          "Replicas": 1
        }
      },
      "EndpointSpec": {
        "Mode": "vip"
      }
    },
    "Endpoint": {
      "Spec": {}
    }
  }
```
You can see that JSON has properties `Mode.Replicated.Replicas`. This maps directly into the properties of the `Service` object that `docker-client` gives you. Docker doesn't return any more information than that. In order to get more information, you have to make more API calls.

Now, you rightly ask, "But doesn't the docker CLI give me more information in one command?" It does give you more in one _command_, but that one command wraps up several API calls. Take a look at the source code for the docker CLI to see what I mean. 

This is the code that gets executed when you call `docker service ls`: https://github.com/docker/cli/blob/master/cli/command/service/list.go
[This line](https://github.com/docker/cli/blob/master/cli/command/service/list.go#L58) is where it calls the `/services` API endpoint. (That's the same endpoint that `docker-client` calls when you do `DockerClient.listServices()`.) But then it goes on to [list all the Tasks](https://github.com/docker/cli/blob/master/cli/command/service/list.go#L72) and [list all the Nodes](https://github.com/docker/cli/blob/master/cli/command/service/list.go#L77), gathers the Task and Node information into a map, then passes that to a function [GetServicesStatus](https://github.com/docker/cli/blob/master/cli/command/service/list.go#L102). The job of that function is essentially to do nothing other than making that `Replicas: x/y` number that you see.

So, in the end, there is no way to use one API call to reproduce the behavior of `docker service ls`. Not even docker can do it in one; they have to use three! On the bright side, by looking at the source of the docker CLI, you can see exactly how they get the number of replicas and you can do the same thing.

**Comment by xiaohesdu** [comment]
@johnflavin Thanks a lot for your reply.

**Comment by davidxia** [comment]
@johnflavin wow thanks for your detailed reply and help. @xiaohesdu it sounds like this answers your question. Can we close the issue?

**Comment by xiaohesdu** [comment]
yes, of course.
